"use client";
import { useState } from "react";
export function Estimator(){
 const [s,setS]=useState(1); const [loading,setLoading]=useState(false); const [done,setDone]=useState(false);
 const [p,setP]=useState({projectType:"vivienda",zone:"gam",area:120,finish:"medio",service:"concepto",goal:"construir",budget:"medio",urgency:"normal",name:"",email:"",phone:"",countryCode:"+506"});
 const u=(k:string,v:any)=>setP(x=>({...x,[k]:v}));
 async function submit(){setLoading(true); const r=await fetch("/api/analyze-project",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}); setLoading(false); if(r.ok){setDone(true);setS(4)}else alert("error");}
 return <section id="evaluacion" className="bg-[#f4f0e8] px-[7vw] py-28">
   <div className="mx-auto max-w-4xl text-center"><p className="mb-4 text-xs font-bold uppercase tracking-[0.22em] text-[#7d735f]">evaluación preliminar</p><h2 className="text-5xl font-black lowercase leading-[0.95] tracking-[-0.06em] md:text-7xl">evalúa tu proyecto antes de cotizar.</h2></div>
   <div className="mx-auto mt-16 max-w-3xl rounded-[2rem] border border-black/10 bg-white/45 p-8 shadow-sm">
   {s===1&&<div className="grid gap-4 md:grid-cols-2"><Select label="tipo" v={p.projectType} set={v=>u("projectType",v)} opts={["vivienda","remodelacion","comercial","inmobiliario","airbnb"]}/><Select label="zona" v={p.zone} set={v=>u("zone",v)} opts={["gam","costera","rural","turistica"]}/><Input label="área m²" v={String(p.area)} set={v=>u("area",Number(v))}/><Select label="acabados" v={p.finish} set={v=>u("finish",v)} opts={["basico","medio","premium","lujo"]}/><button className="button md:col-span-2" onClick={()=>setS(2)}>continuar</button></div>}
   {s===2&&<div className="grid gap-4 md:grid-cols-2"><Select label="servicio" v={p.service} set={v=>u("service",v)} opts={["concepto","planos","renders","integral","obra"]}/><Select label="objetivo" v={p.goal} set={v=>u("goal",v)} opts={["construir","vender","remodelar","validar","rentabilizar"]}/><Select label="presupuesto" v={p.budget} set={v=>u("budget",v)} opts={["bajo","medio","alto","sin_definir"]}/><Select label="urgencia" v={p.urgency} set={v=>u("urgency",v)} opts={["normal","inmediata","exploratoria"]}/><button className="button-secondary" onClick={()=>setS(1)}>atrás</button><button className="button" onClick={()=>setS(3)}>continuar</button></div>}
   {s===3&&<div className="grid gap-4"><Input label="nombre" v={p.name} set={v=>u("name",v)}/><Input label="correo" v={p.email} set={v=>u("email",v)}/><div className="grid grid-cols-[96px_1fr] gap-3"><select className="field" value={p.countryCode} onChange={e=>u("countryCode",e.target.value)}><option value="+506">🇨🇷</option><option value="+1">🇺🇸</option><option value="+52">🇲🇽</option><option value="+57">🇨🇴</option><option value="+34">🇪🇸</option></select><input className="field" placeholder="whatsapp" value={p.phone} onChange={e=>u("phone",e.target.value)}/></div><button className="button-secondary" onClick={()=>setS(2)}>atrás</button><button className="button" onClick={submit}>{loading?"generando...":"generar evaluación"}</button></div>}
   {s===4&&done&&<div><h3 className="text-3xl font-black lowercase">evaluación generada.</h3><p className="mt-4 text-neutral-600">la información fue registrada. vork studio debe revisar el alcance en una sesión inicial.</p><a href="#contacto" className="button mt-8">agendar revisión</a></div>}
   </div>
 </section>
}
function Input({label,v,set}:{label:string;v:string;set:(v:string)=>void}){return <label className="grid gap-2 text-sm font-bold lowercase text-neutral-800">{label}<input className="field" value={v} onChange={e=>set(e.target.value)}/></label>}
function Select({label,v,set,opts}:{label:string;v:string;set:(v:string)=>void;opts:string[]}){return <label className="grid gap-2 text-sm font-bold lowercase text-neutral-800">{label}<select className="field" value={v} onChange={e=>set(e.target.value)}>{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
